echo '-------'
echo 'result of RefBank ping'
curl 'http://localhost:8080/RefBank/rbk/ping'
echo '-------'
echo 'result of RefBank name'
curl 'http://localhost:8080/RefBank/rbk/name'
echo '-------'
echo 'result of RefBank nodes'
curl 'http://localhost:8080/RefBank/rbk/nodes'
echo '-------'
